apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ryhma-4-cluster
  region: eu-west-3

availabilityZones: ["eu-west-3a", "eu-west-3b", "eu-west-3c"]

managedNodeGroups:

  - name: nodegroup
    desiredCapacity: 4
    instanceType: t2.micro
