apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryhma4-server
  labels:
    app: ryhma4-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryhma4
  template:
    metadata:
      labels:
        app: ryhma4
    spec:
      containers:
        - image: supervoltti/ryhma4-server
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 5000
              protocol: TCP
